Feature/routing
humanoidsbv/team-awesome-mark pull request #31
Opened 2022-10-11 08:15 UTC by markbolier

Routing + filter :)

2022-10-11 08:40 UTC, jarmovdh reviewed
Good busy Mark!

2022-10-11 08:40 UTC, jarmovdh commented on src/components/filter/Filter.styled.ts
> +  margin: 10px;
Check some alphabatical sorting 🤪

2022-10-11 08:40 UTC, jarmovdh commented on src/components/filter/Filter.tsx
> +
Nice work

2022-10-11 08:40 UTC, jarmovdh commented on src/components/team-entry-form/TeamEntryForm.tsx
> +          value={newTeamEntry.client ?? ""}
Remove comments from commited work

2022-10-11 09:29 UTC, amijsb requested changes
Good busy! 🚀

2022-10-11 09:29 UTC, amijsb commented on src/components/filter/Filter.tsx
> +  const { teamEntries, setTeamEntries } = useContext(TeamEntriesContext);
Since you don't use `setTeamEntries` you can remove it.

2022-10-11 09:29 UTC, amijsb commented on src/components/filter/Filter.tsx
> +  });
You can shorten this function to 
```suggestion
  const onlyClients = teamEntries.map((entry) => entry.client);
```

2022-10-11 09:29 UTC, amijsb commented on src/components/filter/Filter.tsx
> +  });
I'd also change the name of your variable to something like `clients`; `onlyClients` feels a little verbose in my opinion (and also a little like OnlyFans 😜).

2022-10-11 09:29 UTC, amijsb commented on src/components/filter/Filter.tsx
> +  const formattedClients = [...new Set(onlyClients)];
You could even combine your two variables to just the one: 
```suggestion
  const clients = [...new Set(teamEntries.map((entry) => entry.client))];
```
But it's also fine to keep these two functions separate if you feel like it makes your code more readable.

2022-10-11 09:29 UTC, amijsb commented on src/components/header/Header.tsx
> +        <Link href="/time-sheets" passHref>
It only makes sense to add the `passHref` property if the child of your `<Link />` tag is an `<a />` tag: https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag.

2022-10-11 09:29 UTC, amijsb commented on src/components/team-entries/TeamEntries.tsx
> +  const { teamEntries, setTeamEntries } = useContext(TeamEntriesContext);
Since you don't use `setTeamEntries` you can remove it.

2022-10-11 09:29 UTC, amijsb commented on src/components/team-entries/TeamEntries.tsx
> +    <>
You can remove these fragments (`<></>`) since your container wraps the whole component.

2022-10-11 09:29 UTC, amijsb commented on src/types/types.ts
> +  id?: number;
I don't think the `id` should be an optional property.

2022-10-12 07:24 UTC, amijsb approved these changes

2022-10-12 07:25 UTC, merged